def on_combos_attach_combo():
    pass
controller.combos.attach_combo("", on_combos_attach_combo)

def on_b_pressed():
    global projectile
    pause(350)
    animation.run_image_animation(mySprite,
        [img("""
                .........................
                        .........................
                        .........................
                        .........................
                        .........................
                        .........................
                        .......ffffffffff........
                        .......f77777777f........
                        .......f77777777f........
                        .......f77f77f77f........
                        .....fff77f77f77fff......
                        .....fff777ff777fff......
                        .....fff77777777fff......
                        .......f77777777f........
                        .......ffffffffff........
                        ........ff....ff.........
                        ........ff....ff.........
                        ........ff....ff.........
                        .........................
                        .........................
                        .........................
                        .........................
                        .........................
                        .........................
                        .........................
            """),
            img("""
                .........................
                        .........................
                        .........................
                        .........................
                        .........................
                        .........................
                        .......ffffffffff........
                        .......f77777777f........
                        .......f77777777f........
                        .......f77f77f77f........
                        .....fff77f77f77fff7.....
                        .....fff777ff777fff7.....
                        .....fff77777777fff7.....
                        .......f77777777f........
                        .......ffffffffff........
                        ........ff....ff.........
                        ........ff....ff.........
                        ........ff....ff.........
                        .........................
                        .........................
                        .........................
                        .........................
                        .........................
                        .........................
                        .........................
            """),
            img("""
                .........................
                        .........................
                        .........................
                        .........................
                        .........................
                        .........................
                        .......ffffffffff........
                        .......f77777777f........
                        .......f77777777f........
                        .......f77f77f77f........
                        .....fff77f77f77fff......
                        .....fff777ff777fff......
                        .....fff77777777fff......
                        .......f77777777f........
                        .......ffffffffff........
                        ........ff....ff.........
                        ........ff....ff.........
                        ........ff....ff.........
                        .........................
                        .........................
                        .........................
                        .........................
                        .........................
                        .........................
                        .........................
            """)],
        50,
        False)
    projectile = sprites.create_projectile_from_sprite(assets.image("""
        myImage1
    """), mySprite, 50, 50)
controller.B.on_event(ControllerButtonEvent.PRESSED, on_b_pressed)

def on_combos_attach_combo2():
    global projectile3
    music.zapped.play()
    projectile3 = sprites.create_projectile_from_sprite(img("""
            . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . 6 6 9 9 6 . . . . . . 
                    . . . . 6 6 6 6 9 9 9 . . . . . 
                    . . . 6 6 9 9 6 6 9 9 9 . . . . 
                    . . 6 6 9 9 6 6 6 6 9 9 9 . . . 
                    . 6 6 9 9 9 9 9 6 6 6 9 9 9 . . 
                    . 6 6 9 9 9 9 9 9 9 6 6 9 9 . . 
                    . 6 6 9 9 9 9 9 9 9 6 6 9 9 . . 
                    . 6 6 9 9 9 9 9 9 6 6 9 9 9 . . 
                    . . 6 6 9 9 9 9 9 6 9 9 9 . . . 
                    . . . 6 6 6 9 9 6 6 9 9 . . . . 
                    . . . . 6 6 6 6 6 9 9 . . . . . 
                    . . . . . 6 6 6 6 6 . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        mySprite,
        50,
        50)
controller.combos.attach_combo("" + controller.combos.id_to_string(controller.combos.ID.A) + controller.combos.id_to_string(controller.combos.ID.A) + controller.combos.id_to_string(controller.combos.ID.B),
    on_combos_attach_combo2)

def on_on_zero(status):
    pass
statusbars.on_zero(StatusBarKind.magic, on_on_zero)

def on_combos_attach_special_code():
    pass
controller.combos.attach_special_code(on_combos_attach_special_code)

def on_on_created(sprite):
    pass
sprites.on_created(SpriteKind.player, on_on_created)

projectile3: Sprite = None
projectile: Sprite = None
mySprite: Sprite = None
myEnemy = sprites.create(assets.image("""
    Malware
"""), SpriteKind.enemy)
myEnemy.set_position(110, 105)
tiles.set_current_tilemap(tilemap("""
    minimap
"""))
mySprite = sprites.create(img("""
        . . . . . . . . . . . . . . . . 
            . . . . . f f f f f f f f f f . 
            . . . . . f 7 7 7 7 7 7 7 7 f . 
            . . . . . f 7 7 7 7 7 7 7 7 f . 
            . . . . . f 7 7 f 7 7 f 7 7 f . 
            . . . f f f 7 7 f 7 7 f 7 7 f f 
            . . . f f f 7 7 7 f f 7 7 7 f f 
            . . . . . f 7 7 7 7 7 7 7 7 f . 
            . . . . . f 7 7 7 7 7 7 7 7 f . 
            . . . . . f f f f f f f f f f . 
            . . . . . . f f f . . f f f . . 
            . . . . . . f f f . . f f f . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . .
    """),
    SpriteKind.player)
controller.move_sprite(mySprite, 100, 100)
CHest = sprites.create(assets.image("""
    chEST
"""), SpriteKind.food)
scene.camera_follow_sprite(mySprite)
info.set_life(5)